WITH MAX_SIZE AS(SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, 
                 YEAR(DIFFERENTIATION_DATE) AS YEAR
                 FROM ECOLI_DATA
                 GROUP BY YEAR)

SELECT M.YEAR, (M.MAX_SIZE-E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM MAX_SIZE AS M
right JOIN ECOLI_DATA AS E
ON M.YEAR=YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
