-- 코드를 입력하세요date_format([칼럼 이름], '%Y-%m-%d')
SELECT S.MEMBER_ID, S.MEMBER_NAME, S.GENDER, DATE_FORMAT(S.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE S
WHERE MONTH(S.DATE_OF_BIRTH)=3 AND S.TLNO IS NOT NULL AND S.GENDER='W'
ORDER BY S.MEMBER_ID ASC;